// <auto-generated />
using System;
using Infraestructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infraestructure.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    [Migration("20240507200522_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.ToTable("Category", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Electrodomésticos"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Tecnología y Electrónica"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Moda y Accesorios"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Hogar y Decoración"
                        },
                        new
                        {
                            CategoryId = 5,
                            Name = "Salud y Belleza"
                        },
                        new
                        {
                            CategoryId = 6,
                            Name = "Deportes y Ocio"
                        },
                        new
                        {
                            CategoryId = 7,
                            Name = "Juguetes y Juegos"
                        },
                        new
                        {
                            CategoryId = 8,
                            Name = "Alimentos y Bebidas"
                        },
                        new
                        {
                            CategoryId = 9,
                            Name = "Libros y Material Educativo"
                        },
                        new
                        {
                            CategoryId = 10,
                            Name = "Jardinería y Bricolaje"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal( 15, 2)");

                    b.HasKey("ProductId");

                    b.HasIndex("Category");

                    b.ToTable("Product", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("d5ab1397-8b12-4e48-ab69-dd46df8e3916"),
                            Category = 1,
                            Description = "308L Rt29k577js8 No Frost Ix Inv",
                            Discount = 20,
                            ImageUrl = "https://www.megatone.net/Images/Articulos/zoom2x/36/HEL2958SSG.jpg",
                            Name = "Heladera samsung",
                            Price = 589999m
                        },
                        new
                        {
                            ProductId = new Guid("e93ea063-956e-4950-a2a7-7cdd8370b78f"),
                            Category = 1,
                            Description = "LAvarropas automático WM-85VVC5S6P Inverter vivace 8.5 kg silver",
                            Discount = 10,
                            ImageUrl = "https://76338a6a.flyingcdn.com/44686-large_default/lg-lavarropas-autwm-85vvc5s6p-inverter-vivace-85kg-silver.jpg",
                            Name = "Lg lavarropas automático",
                            Price = 1285713m
                        },
                        new
                        {
                            ProductId = new Guid("37db3c18-d4c9-46dc-9220-35c8e75e35e1"),
                            Category = 1,
                            Description = "Tostadora atma eléctrica toat-39dn",
                            Discount = 0,
                            ImageUrl = "https://76338a6a.flyingcdn.com/39415-large_default/atma-tostadora-electrica-toat-39dn.jpg",
                            Name = "Tostadora",
                            Price = 39999m
                        },
                        new
                        {
                            ProductId = new Guid("dc723fa3-f573-4373-ac2d-fb5068cf300a"),
                            Category = 1,
                            Description = "Batidora atma planetaria bp-at21rp roja",
                            Discount = 0,
                            ImageUrl = "https://76338a6a.flyingcdn.com/42304-large_default/atma-batidora-planetaria-bp-at21rp-roja.jpg",
                            Name = "Batidora planetaria",
                            Price = 589999m
                        },
                        new
                        {
                            ProductId = new Guid("eef25c7a-27fd-4741-8396-fcd2d9f96bf0"),
                            Category = 2,
                            Description = "Smart Tv 50 Pulgadas 4K Ultra Hd 50Pud7406/77 - PHILIPS",
                            Discount = 5,
                            ImageUrl = "https://www.megatone.net/Images/Articulos/zoom2x/253/TEL5006PHI.jpg",
                            Name = "Smart Tv 50 pulgadas 4k",
                            Price = 594099m
                        },
                        new
                        {
                            ProductId = new Guid("5705d26d-a0aa-46ba-9cc8-26db6062a578"),
                            Category = 2,
                            Description = "PS5 SLIM Standard con lector CD/DVD 1TB + 1 Joystick Regalo",
                            Discount = 20,
                            ImageUrl = "https://images.fravega.com/f300/dd39a03cd136501e71f52ef06e09c861.jpg.webp",
                            Name = "Consola Sony PlayStation 5",
                            Price = 900000m
                        },
                        new
                        {
                            ProductId = new Guid("cd8c6422-9773-4a1d-9f80-dc7f7108f16d"),
                            Category = 2,
                            Description = "Proyector Gadnic Surr 5500 Lúmenes Con Filtro HEPA HDMI x 2 USB x 2",
                            Discount = 0,
                            ImageUrl = "https://images.fravega.com/f300/5b68c007ab23568b5379ac7708999b9a.jpg.webp",
                            Name = "Proyector",
                            Price = 283179m
                        },
                        new
                        {
                            ProductId = new Guid("d9cc96bc-c0b3-4662-9b7a-e1350f9329e6"),
                            Category = 2,
                            Description = "Drone Gadnic Con Camara Dual 4K",
                            Discount = 0,
                            ImageUrl = "https://images.fravega.com/f300/60354c20fe3a7afd1b747439ee22d522.jpg.webp",
                            Name = "Drone",
                            Price = 594099m
                        },
                        new
                        {
                            ProductId = new Guid("847ddf9e-edad-48ef-b301-b36a8837c8cf"),
                            Category = 3,
                            Description = "Reebok zapatillas mujer - Glide mujer ch. -Dk grey-green",
                            Discount = 5,
                            ImageUrl = "https://megasports.vteximg.com.br/arquivos/ids/224093-1000-1000/41104788055_0.jpg?v=638267497579500000",
                            Name = "Reebok zapatillas mujer",
                            Price = 99999m
                        },
                        new
                        {
                            ProductId = new Guid("db875506-8544-47f7-b362-a01d272e2243"),
                            Category = 3,
                            Description = "Mochila De Viaje Travel Tech Grande Amplia Compartimientos",
                            Discount = 0,
                            ImageUrl = "https://images.fravega.com/f300/eab6e93f47c2a4a5156964361abd6aa0.jpg.webp",
                            Name = "Mochila de viaje",
                            Price = 104500m
                        },
                        new
                        {
                            ProductId = new Guid("711a840a-ce5a-47c2-9388-4bf507dcdb98"),
                            Category = 3,
                            Description = "Bolso Amayra Fit Cómodo Gimnasio Deportivo",
                            Discount = 0,
                            ImageUrl = "https://images.fravega.com/f300/c60063d66bd91a656af89bf3bf4e0694.jpg.webp",
                            Name = "Bolso deportivo",
                            Price = 30800m
                        },
                        new
                        {
                            ProductId = new Guid("4db7bf99-ded2-430d-957e-b036c2cd5d89"),
                            Category = 3,
                            Description = "Modelo de anteojos de sol para mujer XOLD de la marca RUSTY.",
                            Discount = 15,
                            ImageUrl = "https://static.wixstatic.com/media/617495_87ec75c8071244158aa28802dcdb8108~mv2.jpg/v1/fill/w_500,h_500,al_c,q_80,usm_0.66_1.00_0.01,enc_auto/617495_87ec75c8071244158aa28802dcdb8108~mv2.jpg",
                            Name = "Anteojos de sol",
                            Price = 89600m
                        },
                        new
                        {
                            ProductId = new Guid("186bdb57-0273-42c6-8bc2-1d8e6e10e1a3"),
                            Category = 4,
                            Description = "Lampara Colgante Led L2020 Dorado Moderno Deco Luz Desing",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_Q_NP_660955-MLA74649779983_022024-B.jpg",
                            Name = "Lampara colgante",
                            Price = 99999m
                        },
                        new
                        {
                            ProductId = new Guid("1fe0e417-7a02-4b43-9e9f-34a13a32ea24"),
                            Category = 4,
                            Description = "",
                            Discount = 0,
                            ImageUrl = "https://images.fravega.com/f300/9b2bee9b6b6518b60eb262be396c44fb.jpg.webp",
                            Name = "Juego de Sábanas 1 1/2 plaza Jurassic",
                            Price = 22590m
                        },
                        new
                        {
                            ProductId = new Guid("2aeb3f24-4096-4629-9c45-34ee6b8e743f"),
                            Category = 4,
                            Description = "La almohada de Piero Cervical está hecha de espuma, mejorando la postura del cuello y hombros. Medida: 65 x 35 cm.",
                            Discount = 0,
                            ImageUrl = "https://images.fravega.com/f300/30df4745cef1263ea72604f24c3a3929.jpg.webp",
                            Name = "Almohada de espuma cervical",
                            Price = 14999m
                        },
                        new
                        {
                            ProductId = new Guid("0cc7fc87-36f9-42bb-9855-db85a9527c59"),
                            Category = 4,
                            Description = "Espejo Nam de fibras naturales. Importado de Vietnam Diámetro: 60cm Espejo Diámetro: 19cm",
                            Discount = 10,
                            ImageUrl = "https://images.fravega.com/f300/6c2f4d2d61e3672653e9789598a83334.jpg.webp",
                            Name = "Espejo Nam 60cm",
                            Price = 66990m
                        },
                        new
                        {
                            ProductId = new Guid("1a6d0ffc-ba29-48cd-8197-52ea555da5cd"),
                            Category = 5,
                            Description = "Una fragancia cautivadora nacida de la fusióninesperada entre el dulzor de notas afrutadas, la exclusiva rosatecnológica de Mugler y un elegante collar amaderado.",
                            Discount = 25,
                            ImageUrl = "https://d3cdlnm7te7ky2.cloudfront.net/media/mf_webp/jpg/media/catalog/product/cache/8cafa0a86860701ec5138a548d16cdc2/a/n/angel-nova-edp-rechargable-100ml_1.webp",
                            Name = "Angel nova EDP 100ml",
                            Price = 286000m
                        },
                        new
                        {
                            ProductId = new Guid("7135a466-2efd-4c58-ad8e-7b607ecac5a3"),
                            Category = 5,
                            Description = "La máscara de pestañas Lash Sensational Sky High de larga duración brinda un volumen completo y una longitud ilimitada.",
                            Discount = 0,
                            ImageUrl = "https://d3cdlnm7te7ky2.cloudfront.net/media/mf_webp/jpg/media/catalog/product/cache/d41ed5f2410977369e7cfa45777ef8e0/1/4/142943-a-lash-sensational-sky-high-washable-very-black_1.webp",
                            Name = "Lash sensational sky high washable - very black",
                            Price = 22659m
                        },
                        new
                        {
                            ProductId = new Guid("17a27c35-587f-47f3-9903-d43725566f79"),
                            Category = 5,
                            Description = "Perfume para un hombre que vive en el presente, moldeado por la energía de la modernidad. Imprevisible, sorprende con su originalidad.",
                            Discount = 0,
                            ImageUrl = "https://d3cdlnm7te7ky2.cloudfront.net/media/mf_webp/jpg/media/catalog/product/cache/mtools/300x300/catalog/product//1/1/119078-a-stronger-with-you-edt-100ml_2.webp",
                            Name = "Stronge with you EDT 100ml",
                            Price = 174900m
                        },
                        new
                        {
                            ProductId = new Guid("c16e9685-0cc9-49a8-849f-34cdb93006c6"),
                            Category = 5,
                            Description = "UV defender protector solar facil fuido FPS50+ 40g - claro.UV Defender Fluido es resiste al agua y al sudor, con textura fluida.",
                            Discount = 15,
                            ImageUrl = "https://d3cdlnm7te7ky2.cloudfront.net/media/mf_webp/jpg/media/catalog/product/cache/mtools/300x300/catalog/product//1/5/150122-a-uv-defender-protector-solar-facial-fluido-fps50-40g-claro.webp",
                            Name = "Protector solar facial",
                            Price = 16253m
                        },
                        new
                        {
                            ProductId = new Guid("6ec34474-eda8-432f-b99b-950a8ab69444"),
                            Category = 6,
                            Description = "Bicicleta Mountain Bike X 1.0 Rodado 29 Talle 20 Negro - NORDIC",
                            Discount = 0,
                            ImageUrl = "https://www.megatone.net/Images/Articulos/zoom2x/104/BIC2922NRD.jpg",
                            Name = "Bicicleta mountain bike",
                            Price = 589999m
                        },
                        new
                        {
                            ProductId = new Guid("aad39775-f1c4-47c0-86b2-4c8adabd8b02"),
                            Category = 6,
                            Description = "Soga Saltar Crossfit/fitness Ranbak 737 Azul - RANBAK",
                            Discount = 0,
                            ImageUrl = "https://www.megatone.net/images/Articulos/zoom2x/304/01/MKT0048RAN.jpg",
                            Name = "Soga saltar crossfit",
                            Price = 7300m
                        },
                        new
                        {
                            ProductId = new Guid("ed7df535-73b7-44b2-9553-2cd87b459881"),
                            Category = 6,
                            Description = "Rueda Doble Para Abdominales Ranbak 730 - RANBAK",
                            Discount = 0,
                            ImageUrl = "https://www.megatone.net/images/Articulos/zoom2x/304/01/MKT0060RAN.jpg",
                            Name = "Rueda doble para abdominales",
                            Price = 15799m
                        },
                        new
                        {
                            ProductId = new Guid("d049db6b-ffcf-4ff7-8eed-990bc19e11c2"),
                            Category = 6,
                            Description = "Bote Inflable Explorer Pro 100 22699/0 - INTEX",
                            Discount = 10,
                            ImageUrl = "https://www.megatone.net/Images/Articulos/zoom2x/116/BOT6990ITX.jpg",
                            Name = "Bote inflable",
                            Price = 42999m
                        },
                        new
                        {
                            ProductId = new Guid("2094421c-595f-43d0-b7b3-6423e1628018"),
                            Category = 7,
                            Description = "Dragon Ball Figura 10cm Articulado Flash Super Saiyan Broly",
                            Discount = 0,
                            ImageUrl = "https://wabro.vteximg.com.br/arquivos/ids/187554-320-320/3.jpg?v=638030021553570000",
                            Name = "Broly Dragon ball",
                            Price = 25000m
                        },
                        new
                        {
                            ProductId = new Guid("ccb66f89-a3bb-475f-a8b0-24de4d650fa0"),
                            Category = 7,
                            Description = "Legends of Akedo Powerstorm Battle Giants combina 2 figuras de acción de gigantes de batalla.",
                            Discount = 0,
                            ImageUrl = "https://m.media-amazon.com/images/I/51EXTNFIrYL._AC_.jpg",
                            Name = "Legends of Akedo Powerstorm Battle Giants",
                            Price = 45000m
                        },
                        new
                        {
                            ProductId = new Guid("b76e9bb5-0bed-4c00-861e-5c27a419ac28"),
                            Category = 7,
                            Description = "Hasbro Gaming Simon Juego de memoria electrónica portátil con luces y sonidos para niños de 8 años en adelante",
                            Discount = 0,
                            ImageUrl = "https://m.media-amazon.com/images/I/81P7iHZ+1lL._AC_UL320_.jpg",
                            Name = "Hasbro Gaming Simon Juego de memoria",
                            Price = 30820m
                        },
                        new
                        {
                            ProductId = new Guid("a0175162-22ef-4718-b8db-5e13b0c32966"),
                            Category = 7,
                            Description = "Bloques Magneticos Grandes Varias Formas y colores 42 Piezas MG23",
                            Discount = 15,
                            ImageUrl = "https://images.fravega.com/f300/59412558bc3aad5f4a7e9bcfea3dc30c.jpg.webp",
                            Name = "Bloques magnéticos",
                            Price = 50399m
                        },
                        new
                        {
                            ProductId = new Guid("6641151d-6d69-4c69-ad6c-7481309ca2a8"),
                            Category = 8,
                            Description = "Ferrero Rocher – Chocolate Bombón – 8 Unidades",
                            Discount = 0,
                            ImageUrl = "https://www.argensend.com/wp-content/uploads/2021/09/D_NQ_NP_913338-MLA40945655566_022020-O.jpeg",
                            Name = "Ferrero rocher",
                            Price = 7000m
                        },
                        new
                        {
                            ProductId = new Guid("d74bfd37-7552-4e69-8df4-df771c966a0a"),
                            Category = 8,
                            Description = "ACEITE ORGANICO DE OLIVA 500CC MAELCA",
                            Discount = 10,
                            ImageUrl = "https://biomarket.com.ar/wp-content/uploads/2019/09/7798241870102.jpg",
                            Name = "Aceite de oliva",
                            Price = 12350m
                        },
                        new
                        {
                            ProductId = new Guid("b9ad0df5-af10-467f-a86a-ef509affecee"),
                            Category = 8,
                            Description = "Yogurt de coco sabor arandanos 170 g quimya. Apto veganos",
                            Discount = 0,
                            ImageUrl = "https://biomarket.com.ar/wp-content/uploads/2019/07/721450715893.jpg",
                            Name = "Yogurt de coco sabor arandanos",
                            Price = 2600m
                        },
                        new
                        {
                            ProductId = new Guid("3f009d16-9690-40c6-8853-2823d0f66237"),
                            Category = 8,
                            Description = "Jugo de limón con jengible orgánico 500 cc Las brisas. Apto veganos",
                            Discount = 0,
                            ImageUrl = "https://biomarket.com.ar/wp-content/uploads/2023/01/BRIS54_1.jpg",
                            Name = "Jugo de limón con jengibre",
                            Price = 37930m
                        },
                        new
                        {
                            ProductId = new Guid("d11bc099-419d-4499-8a32-a7598322eea0"),
                            Category = 9,
                            Description = "Faber castell lapices de colores super soft x 24 escritura artística.",
                            Discount = 0,
                            ImageUrl = "https://www.heavenimagenes.com/heavencommerce/11de0e5d-73b3-4c32-910b-8483d00a7205/images/v2/FABER%20CASTELL/3388_medium.jpg",
                            Name = "Lapices de colores",
                            Price = 28500m
                        },
                        new
                        {
                            ProductId = new Guid("5b13da66-b602-4012-a001-d77a79f7494a"),
                            Category = 9,
                            Description = "Mooving agenda 14 x 20 Harry Potter Diaria - Espiralada",
                            Discount = 0,
                            ImageUrl = "https://www.heavenimagenes.com/heavencommerce/11de0e5d-73b3-4c32-910b-8483d00a7205/images/v2/MOOVING/20080_medium.jpg",
                            Name = "Agenda",
                            Price = 25500m
                        },
                        new
                        {
                            ProductId = new Guid("2728192d-a8d1-4b08-b61e-3599efe217f5"),
                            Category = 9,
                            Description = "Casio calculadora científica a bateria FX-82ms",
                            Discount = 20,
                            ImageUrl = "https://www.heavenimagenes.com/heavencommerce/11de0e5d-73b3-4c32-910b-8483d00a7205/images/v2/CASIO/8484_medium.jpg",
                            Name = "Calculadora científica",
                            Price = 29400m
                        },
                        new
                        {
                            ProductId = new Guid("47dc66f0-0db6-4fe4-9c12-adcac5414f54"),
                            Category = 9,
                            Description = "Sifap tempera sólida x 6 pastel arte",
                            Discount = 0,
                            ImageUrl = "https://www.heavenimagenes.com/heavencommerce/11de0e5d-73b3-4c32-910b-8483d00a7205/images/v2/SIFAP/7597_medium.jpg",
                            Name = "Tempera sólida",
                            Price = 12863m
                        },
                        new
                        {
                            ProductId = new Guid("60b80057-efbb-4c9a-8a9a-00784e542ab2"),
                            Category = 10,
                            Description = "Planta de exterior",
                            Discount = 0,
                            ImageUrl = "https://www.viverodeluca.com.ar/1096-home_default/alegria-del-hogar.jpg",
                            Name = "Alegria del hogar",
                            Price = 550m
                        },
                        new
                        {
                            ProductId = new Guid("681b7574-0afd-4db9-a02a-bdbe364dd6f7"),
                            Category = 10,
                            Description = "Cordyline terminalis rubra",
                            Discount = 0,
                            ImageUrl = "https://www.viverodeluca.com.ar/3334-large_default/cordyline-rubra-dracena-rubra-dracena-rubra.jpg",
                            Name = "Dracena rubra",
                            Price = 7900m
                        },
                        new
                        {
                            ProductId = new Guid("aebe2bd8-c7c5-4be9-b704-3357f8af6f52"),
                            Category = 10,
                            Description = "Maceta de barro Clásica - Nº8",
                            Discount = 0,
                            ImageUrl = "https://www.viverodeluca.com.ar/1273-large_default/maceta-de-barro-cl%C3%A1sica.jpg",
                            Name = "Maceta de barro",
                            Price = 940m
                        },
                        new
                        {
                            ProductId = new Guid("3fdf7770-5cde-44ed-a3aa-1d2680008427"),
                            Category = 10,
                            Description = "Desmalezadora Gamma Naftera 44Cc G1835ar - GAMMA",
                            Discount = 15,
                            ImageUrl = "https://www.megatone.net/images//Articulos/zoom2x/106/MKT0013GAM-1.jpg",
                            Name = "Desmalezadora",
                            Price = 242500m
                        });
                });

            modelBuilder.Entity("Domain.Entities.Sale", b =>
                {
                    b.Property<int>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal( 15, 2)");

                    b.Property<decimal>("Taxes")
                        .HasColumnType("decimal( 15, 2)");

                    b.Property<decimal>("TotalDiscount")
                        .HasColumnType("decimal( 15, 2)");

                    b.Property<decimal>("TotalPay")
                        .HasColumnType("decimal( 15, 2)");

                    b.HasKey("SaleId");

                    b.ToTable("Sale", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.SaleProduct", b =>
                {
                    b.Property<int>("ShoppingCartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShoppingCartId"));

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal( 15, 2)");

                    b.Property<Guid>("Product")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Sale")
                        .HasColumnType("int");

                    b.HasKey("ShoppingCartId");

                    b.HasIndex("Product");

                    b.HasIndex("Sale");

                    b.ToTable("SaleProduct", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.HasOne("Domain.Entities.Category", "CategoryName")
                        .WithMany("Products")
                        .HasForeignKey("Category")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoryName");
                });

            modelBuilder.Entity("Domain.Entities.SaleProduct", b =>
                {
                    b.HasOne("Domain.Entities.Product", "ProductName")
                        .WithMany("SaleProducts")
                        .HasForeignKey("Product")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Sale", "SaleName")
                        .WithMany("SaleProducts")
                        .HasForeignKey("Sale")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductName");

                    b.Navigation("SaleName");
                });

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Navigation("SaleProducts");
                });

            modelBuilder.Entity("Domain.Entities.Sale", b =>
                {
                    b.Navigation("SaleProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
