// <auto-generated />
using System;
using Infraestructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infraestructure.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    [Migration("20240602141418_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.ToTable("Category", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Electrodomésticos"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Tecnología y Electrónica"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Moda y Accesorios"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Hogar y Decoración"
                        },
                        new
                        {
                            CategoryId = 5,
                            Name = "Salud y Belleza"
                        },
                        new
                        {
                            CategoryId = 6,
                            Name = "Deportes y Ocio"
                        },
                        new
                        {
                            CategoryId = 7,
                            Name = "Juguetes y Juegos"
                        },
                        new
                        {
                            CategoryId = 8,
                            Name = "Alimentos y Bebidas"
                        },
                        new
                        {
                            CategoryId = 9,
                            Name = "Libros y Material Educativo"
                        },
                        new
                        {
                            CategoryId = 10,
                            Name = "Jardinería y Bricolaje"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal( 15, 2)");

                    b.HasKey("ProductId");

                    b.HasIndex("Category");

                    b.ToTable("Product", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("c5fd9f72-7baf-40f5-ad4f-1007e98ba61e"),
                            Category = 1,
                            Description = "308L Rt29k577js8 No Frost Ix Inv",
                            Discount = 20,
                            ImageUrl = "https://www.megatone.net/Images/Articulos/zoom2x/36/HEL2958SSG.jpg",
                            Name = "Heladera samsung 308L",
                            Price = 589999m
                        },
                        new
                        {
                            ProductId = new Guid("fb6d807a-cb90-488d-906e-e00c9b18f636"),
                            Category = 1,
                            Description = "LAvarropas automático WM-85VVC5S6P Inverter vivace 8.5 kg silver",
                            Discount = 30,
                            ImageUrl = "https://www.perozzi.com.ar/44686-large_default/lg-lavarropas-autwm-85vvc5s6p-inverter-vivace-85kg-silver.jpg",
                            Name = "Lg lavarropas automático 8.5 kg",
                            Price = 1285713m
                        },
                        new
                        {
                            ProductId = new Guid("717dc797-619f-448c-b7d1-2d04f5230e96"),
                            Category = 1,
                            Description = "La tostadora Disney tiene un diseño moderno, liviano de color rojo. Hacé las tostadas mas originales con la cara de Mickey Mouse y disfrutá de tus desayunos y meriendas de la manera más divertida. Brinda 7 niveles de tostado y es fácil de limpiar ya que viene con bandeja de migas.",
                            Discount = 15,
                            ImageUrl = "https://www.perozzi.com.ar/39420-large_default/atma-tostadora-electrica-toat-39dn.jpg",
                            Name = "Tostadora atma eléctrica toat-39dn",
                            Price = 39999m
                        },
                        new
                        {
                            ProductId = new Guid("1f2a9e14-928a-4b35-b2c9-9295e15839d6"),
                            Category = 1,
                            Description = "Descripción: 8 niveles de potencia-movimiento planetario para amasado,mezcla y batido-\r\nMarca: Ultracomb\r\nOrigen: Argentina\r\nFunciones: bol acero inoxidable\r\nMateriales: N/A\r\nGarantia de Fabrica (meses): 6\r\nCapacidad: 5 Litros\r\nPotencia (Watts): 800 w\r\naccesorios: 3 accesorios/cabezal rebatible",
                            Discount = 20,
                            ImageUrl = "https://www.perozzi.com.ar/16649-large_default/ultracomb-batidora-planetaria-gris-bb-2106-37801109.jpg",
                            Name = "Ultracomb batidora planetario Gris BB 2106",
                            Price = 589999m
                        },
                        new
                        {
                            ProductId = new Guid("2ffb0678-7074-4806-ae3b-b1d11b8981c9"),
                            Category = 2,
                            Description = "Smart Tv 50 Pulgadas 4K Ultra Hd 50Pud7406/77 - PHILIPS",
                            Discount = 25,
                            ImageUrl = "https://www.megatone.net/Images/Articulos/zoom2x/253/TEL5006PHI.jpg",
                            Name = "Smart Tv 50 pulgadas 4k",
                            Price = 594099m
                        },
                        new
                        {
                            ProductId = new Guid("5b5428d3-b783-4bb3-b940-4dedc4812809"),
                            Category = 2,
                            Description = "PS5 SLIM Standard con lector CD/DVD 1TB + 1 Joystick Regalo",
                            Discount = 20,
                            ImageUrl = "https://images.fravega.com/f300/dd39a03cd136501e71f52ef06e09c861.jpg.webp",
                            Name = "Consola Sony PlayStation 5",
                            Price = 900000m
                        },
                        new
                        {
                            ProductId = new Guid("0ec581e2-a70e-40fc-bdc5-115ac6554aa7"),
                            Category = 2,
                            Description = "Proyector Gadnic Surr 5500 Lúmenes Con Filtro HEPA HDMI x 2 USB x 2",
                            Discount = 20,
                            ImageUrl = "https://images.fravega.com/f300/5b68c007ab23568b5379ac7708999b9a.jpg.webp",
                            Name = "Proyector Gadnic Surr 5500",
                            Price = 283179m
                        },
                        new
                        {
                            ProductId = new Guid("5e15a6c2-450d-4c80-87c3-a3e5715ce1f9"),
                            Category = 2,
                            Description = "Drone Gadnic Con Camara Dual 4K",
                            Discount = 30,
                            ImageUrl = "https://images.fravega.com/f300/60354c20fe3a7afd1b747439ee22d522.jpg.webp",
                            Name = "Drone Gadnic 4k",
                            Price = 594099m
                        },
                        new
                        {
                            ProductId = new Guid("3c453d3b-be0f-451b-935a-3074d49d499c"),
                            Category = 3,
                            Description = "Reebok zapatillas mujer - Glide mujer ch. -Dk grey-green",
                            Discount = 25,
                            ImageUrl = "https://megasports.vteximg.com.br/arquivos/ids/224093-1000-1000/41104788055_0.jpg?v=638267497579500000",
                            Name = "Zapatillas reebok glide mujer",
                            Price = 99999m
                        },
                        new
                        {
                            ProductId = new Guid("423064ab-e4c9-43df-9890-b5d290af3b76"),
                            Category = 3,
                            Description = "Mochila Plegable Travel Tech Viajes Práctica Liviana Cecchini es una empresa marroquinera con presencia en el mercado desde el año 1991. Creada en Rosario hoy cuenta con puntos de ventas en distintas partes del país como San Lorenzo, Villa Gobernador Gálvez, Venado Tuerto, Paraná, Santa Fe, Neuquén y CABA. Características: Confección: Material 100% poliéster Dimensiones de la mochila plegada: alto 18 cm x ancho 20 cm x profundidad 2 cm Dimensiones de la mochila abierta: alto 42 cm x ancho 29cm x profundidad 12 cm",
                            Discount = 10,
                            ImageUrl = "https://images.fravega.com/f300/eab6e93f47c2a4a5156964361abd6aa0.jpg.webp",
                            Name = "Mochila de viaje travel tech",
                            Price = 104500m
                        },
                        new
                        {
                            ProductId = new Guid("10c9611b-c709-4464-ba4e-4602204c616e"),
                            Category = 3,
                            Description = "Bolso Amayra Fit Cómodo Gimnasio Deportivo",
                            Discount = 0,
                            ImageUrl = "https://images.fravega.com/f300/c60063d66bd91a656af89bf3bf4e0694.jpg.webp",
                            Name = "Bolso deportivo Amayra",
                            Price = 30800m
                        },
                        new
                        {
                            ProductId = new Guid("f4b8dbb4-7ce3-497f-99a7-8a1c805c9d71"),
                            Category = 3,
                            Description = "Modelo de anteojos de sol para mujer XOLD de la marca RUSTY.",
                            Discount = 15,
                            ImageUrl = "https://static.wixstatic.com/media/617495_87ec75c8071244158aa28802dcdb8108~mv2.jpg/v1/fill/w_500,h_500,al_c,q_80,usm_0.66_1.00_0.01,enc_auto/617495_87ec75c8071244158aa28802dcdb8108~mv2.jpg",
                            Name = "Anteojos de sol XOLD Rusty ",
                            Price = 89600m
                        },
                        new
                        {
                            ProductId = new Guid("ec732784-5f80-442d-bc4c-3a0839486cbe"),
                            Category = 4,
                            Description = "Lampara Colgante Led L2020 Dorado Moderno Deco Luz Desing",
                            Discount = 20,
                            ImageUrl = "https://http2.mlstatic.com/D_Q_NP_660955-MLA74649779983_022024-B.jpg",
                            Name = "Lampara colgante L2020",
                            Price = 99999m
                        },
                        new
                        {
                            ProductId = new Guid("9716cbbc-f372-49ca-96e6-2f21c9b7b30e"),
                            Category = 4,
                            Description = "",
                            Discount = 10,
                            ImageUrl = "https://images.fravega.com/f300/9b2bee9b6b6518b60eb262be396c44fb.jpg.webp",
                            Name = "Juego de Sábanas 1 1/2 plaza Jurassic",
                            Price = 22590m
                        },
                        new
                        {
                            ProductId = new Guid("5611d608-f438-4caf-a22b-8c73317d4496"),
                            Category = 4,
                            Description = "La almohada de Piero Cervical está hecha de espuma, mejorando la postura del cuello y hombros. Medida: 65 x 35 cm.",
                            Discount = 15,
                            ImageUrl = "https://images.fravega.com/f300/30df4745cef1263ea72604f24c3a3929.jpg.webp",
                            Name = "Almohada de espuma cervical",
                            Price = 14999m
                        },
                        new
                        {
                            ProductId = new Guid("62ef7a6f-98c6-4677-9920-335f9dfb7be8"),
                            Category = 4,
                            Description = "Espejo Nam de fibras naturales. Importado de Vietnam Diámetro: 60cm Espejo Diámetro: 19cm",
                            Discount = 10,
                            ImageUrl = "https://images.fravega.com/f300/6c2f4d2d61e3672653e9789598a83334.jpg.webp",
                            Name = "Espejo Nam 60cm",
                            Price = 66990m
                        },
                        new
                        {
                            ProductId = new Guid("1f3fb438-bd1b-4fea-b8e8-2b7f51546967"),
                            Category = 5,
                            Description = "Una fragancia cautivadora nacida de la fusióninesperada entre el dulzor de notas afrutadas, la exclusiva rosatecnológica de Mugler y un elegante collar amaderado.",
                            Discount = 25,
                            ImageUrl = "https://d3cdlnm7te7ky2.cloudfront.net/media/mf_webp/jpg/media/catalog/product/cache/8cafa0a86860701ec5138a548d16cdc2/a/n/angel-nova-edp-rechargable-100ml_1.webp",
                            Name = "Perfume Angel nova EDP 100ml",
                            Price = 286000m
                        },
                        new
                        {
                            ProductId = new Guid("ddfb8fb4-8959-42c1-9679-f9fe5ec8286b"),
                            Category = 5,
                            Description = "La máscara de pestañas Lash Sensational Sky High de larga duración brinda un volumen completo y una longitud ilimitada.",
                            Discount = 10,
                            ImageUrl = "https://d3cdlnm7te7ky2.cloudfront.net/media/mf_webp/jpg/media/catalog/product/cache/d41ed5f2410977369e7cfa45777ef8e0/1/4/142943-a-lash-sensational-sky-high-washable-very-black_1.webp",
                            Name = "Lash sensational sky high washable - very black",
                            Price = 22659m
                        },
                        new
                        {
                            ProductId = new Guid("200a1994-0bda-4fb5-890f-f5106568a52c"),
                            Category = 5,
                            Description = "Perfume para un hombre que vive en el presente, moldeado por la energía de la modernidad. Imprevisible, sorprende con su originalidad.",
                            Discount = 25,
                            ImageUrl = "https://d3cdlnm7te7ky2.cloudfront.net/media/mf_webp/jpg/media/catalog/product/cache/mtools/300x300/catalog/product//1/1/119078-a-stronger-with-you-edt-100ml_2.webp",
                            Name = "Perfume Stronge with you EDT 100ml",
                            Price = 174900m
                        },
                        new
                        {
                            ProductId = new Guid("bd369db5-8f06-4aef-a147-5adf28905227"),
                            Category = 5,
                            Description = "UV defender protector solar facil fuido FPS50+ 40g - claro.UV Defender Fluido es resiste al agua y al sudor, con textura fluida.",
                            Discount = 15,
                            ImageUrl = "https://d3cdlnm7te7ky2.cloudfront.net/media/mf_webp/jpg/media/catalog/product/cache/mtools/300x300/catalog/product//1/5/150122-a-uv-defender-protector-solar-facial-fluido-fps50-40g-claro.webp",
                            Name = "Protector solar facial UV defender",
                            Price = 16253m
                        },
                        new
                        {
                            ProductId = new Guid("182b0b89-3168-4fa2-8b60-bd3bea918840"),
                            Category = 6,
                            Description = "Bicicleta Mountain Bike X 1.0 Rodado 29 Talle 20 Negro - NORDIC",
                            Discount = 25,
                            ImageUrl = "https://www.megatone.net/Images/Articulos/zoom2x/104/BIC2922NRD.jpg",
                            Name = "Bicicleta mountain bike rodado 29",
                            Price = 589999m
                        },
                        new
                        {
                            ProductId = new Guid("0ef3c3ce-d2b8-43f1-9f77-b2d80dc1a893"),
                            Category = 6,
                            Description = "Soga Saltar Crossfit/fitness Ranbak 737 Azul - RANBAK",
                            Discount = 0,
                            ImageUrl = "https://www.megatone.net/images/Articulos/zoom2x/304/01/MKT0048RAN.jpg",
                            Name = "Soga saltar crossfit Ranbak",
                            Price = 7300m
                        },
                        new
                        {
                            ProductId = new Guid("194404ce-d7ac-4909-99c4-fa539bdd8db4"),
                            Category = 6,
                            Description = "Rueda Doble Para Abdominales Ranbak 730 - RANBAK",
                            Discount = 10,
                            ImageUrl = "https://www.megatone.net/images/Articulos/zoom2x/304/01/MKT0060RAN.jpg",
                            Name = "Rueda doble para abdominales Ranbak",
                            Price = 15799m
                        },
                        new
                        {
                            ProductId = new Guid("ebce1337-8dfc-4499-861a-b3900932b0c9"),
                            Category = 6,
                            Description = "Bote Inflable Explorer Pro 100 22699/0 - INTEX",
                            Discount = 10,
                            ImageUrl = "https://www.megatone.net/Images/Articulos/zoom2x/116/BOT6990ITX.jpg",
                            Name = "Bote inflable intex",
                            Price = 42999m
                        },
                        new
                        {
                            ProductId = new Guid("1ae43399-86c2-4a42-84fe-e46bd2dd6786"),
                            Category = 7,
                            Description = "Dragon Ball Figura 10cm Articulado Flash Super Saiyan Broly",
                            Discount = 10,
                            ImageUrl = "https://wabro.vteximg.com.br/arquivos/ids/187554-320-320/3.jpg?v=638030021553570000",
                            Name = "Broly Dragon ball",
                            Price = 25000m
                        },
                        new
                        {
                            ProductId = new Guid("c5bc982d-5219-492d-8c4f-24910ce2b42d"),
                            Category = 7,
                            Description = "Legends of Akedo Powerstorm Battle Giants combina 2 figuras de acción de gigantes de batalla.",
                            Discount = 15,
                            ImageUrl = "https://m.media-amazon.com/images/I/51EXTNFIrYL._AC_.jpg",
                            Name = "Legends of Akedo Powerstorm Battle Giants",
                            Price = 45000m
                        },
                        new
                        {
                            ProductId = new Guid("3f14062b-1681-4f5c-8fb2-39094b9b1465"),
                            Category = 7,
                            Description = "Hasbro Gaming Simon Juego de memoria electrónica portátil con luces y sonidos para niños de 8 años en adelante",
                            Discount = 10,
                            ImageUrl = "https://m.media-amazon.com/images/I/81P7iHZ+1lL._AC_UL320_.jpg",
                            Name = "Hasbro Gaming Simon Juego de memoria",
                            Price = 30820m
                        },
                        new
                        {
                            ProductId = new Guid("4e85ec95-48cc-4fde-8070-8c2672610a97"),
                            Category = 7,
                            Description = "Bloques Magneticos Grandes Varias Formas y colores 42 Piezas MG23",
                            Discount = 20,
                            ImageUrl = "https://images.fravega.com/f300/59412558bc3aad5f4a7e9bcfea3dc30c.jpg.webp",
                            Name = "Bloques magnéticos",
                            Price = 50399m
                        },
                        new
                        {
                            ProductId = new Guid("fe2f9a1e-898b-4295-8f1f-d1c905d26fac"),
                            Category = 8,
                            Description = "Ferrero Rocher – Chocolate Bombón – 8 Unidades",
                            Discount = 0,
                            ImageUrl = "https://www.argensend.com/wp-content/uploads/2021/09/D_NQ_NP_913338-MLA40945655566_022020-O.jpeg",
                            Name = "Ferrero rocher",
                            Price = 7000m
                        },
                        new
                        {
                            ProductId = new Guid("478c2636-c4b5-422d-be08-515f45f72477"),
                            Category = 8,
                            Description = "ACEITE ORGANICO DE OLIVA 500CC MAELCA",
                            Discount = 15,
                            ImageUrl = "https://biomarket.com.ar/wp-content/uploads/2019/09/7798241870102.jpg",
                            Name = "Aceite de oliva",
                            Price = 12350m
                        },
                        new
                        {
                            ProductId = new Guid("bc86ec6f-2fcf-4413-8ea5-d166b434efef"),
                            Category = 8,
                            Description = "Yogurt de coco sabor arandanos 170 g quimya. Apto veganos",
                            Discount = 0,
                            ImageUrl = "https://biomarket.com.ar/wp-content/uploads/2019/07/721450715893.jpg",
                            Name = "Yogurt de coco sabor arandanos",
                            Price = 2600m
                        },
                        new
                        {
                            ProductId = new Guid("91ff3094-a179-40c5-be6d-d856b06ad382"),
                            Category = 8,
                            Description = "Jugo de limón con jengible orgánico 500 cc Las brisas. Apto veganos",
                            Discount = 0,
                            ImageUrl = "https://biomarket.com.ar/wp-content/uploads/2023/01/BRIS54_1.jpg",
                            Name = "Jugo de limón con jengibre",
                            Price = 3793m
                        },
                        new
                        {
                            ProductId = new Guid("66d17410-8f3b-47e2-ac63-b1d5d9bce938"),
                            Category = 9,
                            Description = "Faber castell lapices de colores super soft x 24 escritura artística.",
                            Discount = 0,
                            ImageUrl = "https://www.heavenimagenes.com/heavencommerce/11de0e5d-73b3-4c32-910b-8483d00a7205/images/v2/FABER%20CASTELL/3388_medium.jpg",
                            Name = "Lapices de colores",
                            Price = 28500m
                        },
                        new
                        {
                            ProductId = new Guid("d4511e5c-ca7d-47f8-bd0c-4f4285fcb130"),
                            Category = 9,
                            Description = "Mooving agenda 14 x 20 Harry Potter Diaria - Espiralada",
                            Discount = 15,
                            ImageUrl = "https://www.heavenimagenes.com/heavencommerce/11de0e5d-73b3-4c32-910b-8483d00a7205/images/v2/MOOVING/20080_medium.jpg",
                            Name = "Agenda",
                            Price = 25500m
                        },
                        new
                        {
                            ProductId = new Guid("5f645fd6-67d8-482c-a6f5-24a4822b3714"),
                            Category = 9,
                            Description = "Casio calculadora científica a bateria FX-82ms",
                            Discount = 20,
                            ImageUrl = "https://www.heavenimagenes.com/heavencommerce/11de0e5d-73b3-4c32-910b-8483d00a7205/images/v2/CASIO/8484_medium.jpg",
                            Name = "Calculadora científica",
                            Price = 29400m
                        },
                        new
                        {
                            ProductId = new Guid("10fbd907-a04e-4928-9857-e3dd2d37b98f"),
                            Category = 9,
                            Description = "Sifap tempera sólida x 6 pastel arte",
                            Discount = 0,
                            ImageUrl = "https://www.heavenimagenes.com/heavencommerce/11de0e5d-73b3-4c32-910b-8483d00a7205/images/v2/SIFAP/7597_medium.jpg",
                            Name = "Tempera sólida",
                            Price = 12863m
                        },
                        new
                        {
                            ProductId = new Guid("d4968223-01dc-477d-93da-cc237f917a00"),
                            Category = 10,
                            Description = "La Impatiens walleriana, comúnmente conocida como ‘Alegría del hogar’, es una planta que se distingue por su belleza ornamental y su fácil cultivo.",
                            Discount = 0,
                            ImageUrl = "https://th.bing.com/th/id/OIP.ESv3sAmz6E3HL_WFTlqcfQHaHa?rs=1&pid=ImgDetMain",
                            Name = "Alegria del hogar",
                            Price = 550m
                        },
                        new
                        {
                            ProductId = new Guid("501be9fb-78f2-4a84-a9e4-9402bb4021c4"),
                            Category = 10,
                            Description = "Astrophytum asterias es un cactus sin espinas que puebla las regiones del sur de Estados Unidos y el norte de México. De tamaño pequeño, es considerado como una especie en peligro de extinción.",
                            Discount = 10,
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcTG8NlAr6uybZn0eXG-xCGU5wpnAB97GpN7z4m7cJF0LYCirk_Li9eSfzBJ1ci8yHlBI5URFnlg84H57G9vPsmAlekPMBTJwoPP1iwXOcuo&usqp=CAE",
                            Name = "Cactus Asteria Variegata",
                            Price = 30000m
                        },
                        new
                        {
                            ProductId = new Guid("fa6d0760-d688-4695-9d40-1bcf47e25b9a"),
                            Category = 10,
                            Description = "Esta maceta de barro rojo tipo coco está diseñada como maceta de suelo. Cuenta con orificio para drenaje del agua. También puede ser utilizada como macetero o cubremaceta, albergando en su interior otras macetas de menores dimensiones. Se ofrece en un diámetro de 23 cm,",
                            Discount = 0,
                            ImageUrl = "https://www.ceramicaramblena.com/wp-content/uploads/2021/11/coco-terracota-maceta-grande-modelo-03-01-510x382.jpg",
                            Name = "Coco terracota – Maceta grande – Modelo 03",
                            Price = 6000m
                        },
                        new
                        {
                            ProductId = new Guid("979162bc-3625-48d7-8530-54cef526a34b"),
                            Category = 10,
                            Description = "Desmalezadora Gamma Naftera 44Cc G1835ar - GAMMA",
                            Discount = 15,
                            ImageUrl = "https://www.megatone.net/images//Articulos/zoom2x/106/MKT0013GAM-1.jpg",
                            Name = "Desmalezadora",
                            Price = 242500m
                        });
                });

            modelBuilder.Entity("Domain.Entities.Sale", b =>
                {
                    b.Property<int>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal( 15, 2)");

                    b.Property<decimal>("Taxes")
                        .HasColumnType("decimal( 15, 2)");

                    b.Property<decimal>("TotalDiscount")
                        .HasColumnType("decimal( 15, 2)");

                    b.Property<decimal>("TotalPay")
                        .HasColumnType("decimal( 15, 2)");

                    b.HasKey("SaleId");

                    b.ToTable("Sale", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.SaleProduct", b =>
                {
                    b.Property<int>("ShoppingCartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShoppingCartId"));

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal( 15, 2)");

                    b.Property<Guid>("Product")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Sale")
                        .HasColumnType("int");

                    b.HasKey("ShoppingCartId");

                    b.HasIndex("Product");

                    b.HasIndex("Sale");

                    b.ToTable("SaleProduct", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.HasOne("Domain.Entities.Category", "CategoryName")
                        .WithMany("Products")
                        .HasForeignKey("Category")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoryName");
                });

            modelBuilder.Entity("Domain.Entities.SaleProduct", b =>
                {
                    b.HasOne("Domain.Entities.Product", "ProductName")
                        .WithMany("SaleProducts")
                        .HasForeignKey("Product")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Sale", "SaleName")
                        .WithMany("SaleProducts")
                        .HasForeignKey("Sale")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductName");

                    b.Navigation("SaleName");
                });

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Navigation("SaleProducts");
                });

            modelBuilder.Entity("Domain.Entities.Sale", b =>
                {
                    b.Navigation("SaleProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
